version: '3.8'
services:
  db:
    image: postgres
    container_name: helpdesk-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helpdesk
    ports:
      - "5432:5432"